server.port=8083
spring.application.name=credibanco-backend

# Conexión a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/credibanco
spring.datasource.username=postgres
spring.datasource.password=postgres

# Dialecto JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Formato y mostra SQL en consola para depuración
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Estrategia para crear/actualizar el esquema (usa 'none' si ya lo creaste manualmente)
spring.jpa.hibernate.ddl-auto=none

# Zona horaria (ajústalo a tu zona si tienes fechas en los modelos)
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota
